
server.port=8081
# Aumentado para soportar multiples anexos de mas de 100MB cada uno
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB

# Configuracion JWT
app.jwt.secret=mySecretKey12345678901234567890123456789012345678901234567890
#app.jwt.expiration=86400000
app.jwt.expiration=1800000
# 86400000 ms = 24 horas




# postgres
spring.datasource.url=jdbc:postgresql://192.168.3.23:5432/sgd-emapat
spring.datasource.username=IDOSGD
spring.datasource.password=Qbcsac++4223
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Logging
#logging.level.org.springframework.security=DEBUG
#logging.level.com.emtap.mesapartes=DEBUG


#spring.docker.compose.enabled=true
#spring.docker.compose.file=docker-compose.yml

# ============================================================
# CONFIGURACION DE CORREO - Mesa de Partes Virtual
# ============================================================

# Cuenta 1: tramite.documentario → envía notificación a mesadepartesvirtual
mail.tramite.username=sgd.tramitedoc@emapat.com.pe
mail.tramite.password=bhbdojwjgwgeifyj

# Cuenta 2: mesadepartesvirtual → envía respuesta al ciudadano
mail.mesapartes.username=mesadepartes@emapat.com.pe
mail.mesapartes.password=Njimen@z2025

# URL base de la API (para los botones Aceptar/Rechazar del correo)
app.base-url=https://api-sgd.epsgrau.pe:9000
app.correo.tramite=sgd.tramitedoc@emapat.com.pe
app.correo.mesapartes=mesadepartes@emapat.com.pe


#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=wlana7c8
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=miappssl

